name: '${name}'
version: '${version}'
main: 'net.streamline.base.Streamline'

authors: [ Drak ]
website: https://github.com/Streamline-Essentials
description: True potential is here. A Proxy and Spigot plugin that opens up endless cross-platform possibilities.

depend:
  - LuckPerms
  - BukkitOfUtils
soft-depend:
  - Geyser-Spigot
  - Geyser-Folia
  - PlaceholderAPI
  - floodgate
  - CMI
  - EssentialsX
  - Essentials

folia-supported: true

commands:
  streamlinespigot:
    description: Main command for Streamline
    permission: streamline.command.base.default
    aliases:
      - sls
      - streamline
      - sl