package singularity.data.players.events;

import lombok.Getter;
import lombok.Setter;
import singularity.data.console.CosmicSender;
import singularity.data.players.CosmicPlayer;
import singularity.events.CosmicEvent;

/**
 * Base event class carrying a reference to the {@link CosmicSender} that triggered
 * the event.
 *
 * <p>All sender-scoped lifecycle events (create, load, save, unload, delete) extend
 * this class. Convenience helpers let callers determine whether the sender is a
 * full {@link CosmicPlayer} and obtain the typed reference without an explicit cast.</p>
 *
 * <p>The {@code sender} field and its accessor are generated by Lombok via
 * {@code @Getter}/{@code @Setter}.</p>
 */
@Getter @Setter
public class CosmicSenderEvent extends CosmicEvent {

    /**
     * The sender associated with this event. May be a {@link CosmicPlayer} if the
     * originating entity is an online player.
     */
    private CosmicSender sender;

    /**
     * Constructs a {@code CosmicSenderEvent} for the given sender.
     *
     * @param sender the {@link CosmicSender} that triggered this event
     */
    public CosmicSenderEvent(CosmicSender sender) {
        this.sender = sender;
    }

    /**
     * Returns {@code true} if the underlying sender is an instance of
     * {@link CosmicPlayer}.
     *
     * @return {@code true} when the sender is a player, {@code false} for
     *         non-player senders such as the console
     */
    public boolean isPlayer() {
        return sender instanceof CosmicPlayer;
    }

    /**
     * Returns the sender cast to {@link CosmicPlayer}, or {@code null} if the
     * sender is not a player. Callers should check {@link #isPlayer()} before
     * invoking this method.
     *
     * @return the {@link CosmicPlayer} instance, or {@code null}
     */
    public CosmicPlayer getPlayer() {
        if (! isPlayer()) return null;

        return (CosmicPlayer) sender;
    }
}
