package singularity.data.players.events;

import lombok.Getter;
import lombok.Setter;
import singularity.data.players.CosmicPlayer;

/**
 * Event fired when a {@link CosmicPlayer}'s display name is updated.
 *
 * <p>This event carries both the previous name ({@code changeFrom}) and the
 * requested new name ({@code changeTo}). Listeners may modify {@code changeTo}
 * before the change is applied, enabling name filtering or formatting pipelines.</p>
 *
 * <p>The {@code changeTo} and {@code changeFrom} fields and their accessors are
 * generated by Lombok via {@code @Getter}/{@code @Setter}. Note that
 * {@code changeFrom} is {@code final} and therefore only has a getter.</p>
 *
 * <p>For name changes triggered by a proxied cross-server message, see the subclass
 * {@link UserNameUpdateByOtherEvent}.</p>
 */
@Getter @Setter
public class UserNameUpdateEvent extends CosmicSenderEvent {

    /**
     * The name the player is being changed to. Listeners may alter this value
     * before the update is committed.
     */
    private String changeTo;

    /**
     * The player's name before the update was requested. This value is immutable
     * once the event is constructed.
     */
    private final String changeFrom;

    /**
     * Constructs a {@code UserNameUpdateEvent} for the given player, recording
     * both the old and requested new display names.
     *
     * @param player     the {@link CosmicPlayer} whose name is being updated
     * @param changeTo   the new name being applied
     * @param changeFrom the player's current name before the update
     */
    public UserNameUpdateEvent(CosmicPlayer player, String changeTo, String changeFrom) {
        super(player);
        this.changeTo = changeTo;
        this.changeFrom = changeFrom;
    }
}
