package singularity.data.players.events;

import lombok.Getter;
import lombok.Setter;
import singularity.data.players.CosmicPlayer;
import singularity.messages.proxied.ProxiedMessage;

/**
 * Event fired when a {@link CosmicPlayer}'s display name is updated via a
 * cross-server proxied message rather than a local action.
 *
 * <p>This subclass of {@link UserNameUpdateEvent} carries the originating
 * {@link ProxiedMessage} so that listeners can identify the source server or
 * channel that initiated the name change. The {@code proxiedMessage} field and
 * its accessor are generated by Lombok via {@code @Getter}/{@code @Setter}.</p>
 */
@Getter @Setter
public class UserNameUpdateByOtherEvent extends UserNameUpdateEvent {

    /**
     * The proxied message that triggered this name-change request, providing
     * metadata about the originating server and message channel.
     */
    ProxiedMessage proxiedMessage;

    /**
     * Constructs a {@code UserNameUpdateByOtherEvent} carrying both the name-change
     * details and the source proxied message.
     *
     * @param user           the {@link CosmicPlayer} whose name is being updated
     * @param changeTo       the new name being applied
     * @param changeFrom     the player's current name before the update
     * @param proxiedMessage the {@link ProxiedMessage} that originated this change
     */
    public UserNameUpdateByOtherEvent(CosmicPlayer user, String changeTo, String changeFrom, ProxiedMessage proxiedMessage) {
        super(user, changeTo, changeFrom);

        this.proxiedMessage = proxiedMessage;
    }
}
