# Settings for the console sender.
console:
  # Name of the console sender.
  name: "Console"
  # Display name of the console sender.
  display-name: "&c&lConsole&r"
  # The 'UUID' of the console sender.
  discriminator: "%"
  # The server to be shown as the
  # console sender's server.
  server: "space"

# Settings for actual player users.
players:
  meta:
    nickname: ""
    prefix: ""
    suffix: ""
  # Settings for player user names.
  name:
    # Enables formatting player usernames (with colors, nicks, etc.)
    formatted: true
    online: "&d%streamline_user_formatted% &a&l•&r"
    offline: "&d%streamline_user_formatted% &c&l•&r"
  # Settings for all things experience-based with player users.
  experience:
    # Settings for announcing things with experience.
    announce:
      # Settings for announcing level changes.
      level-change:
        # If we should tell them with a title.
        title: true
        # If we should tell them with a chat message.
        chat: false
    # Settings for the payout of experience. (Adding or removing experience to or from player users.)
    payout:
      # The amount to add every payout. Works with negative numbers!
      # -10 = subtracts 10 xp every payout period.
      # 10 = adds 10 xp every payout period.
      amount: 1.0
      # The amount of time (in server ticks; 20 ticks per second) to run a payout after. (Repeats.)
      # 400 = every 20 seconds. (DEFAULT.)
      every: 400
    # Settings for the starting xp and level for when a player user profile is first created.
    starting:
      # The starting level.
      # Leveling equation can be configured below.
      level: 1
      # The starting xp amount.
      # Leveling equation can be configured below.
      xp: 0
    # The equation to use when calculating level up.
    equation: "2500 + (2500 * (%streamline_user_level% - 1))"
  # Settings for tags.
  # Tags are a list of Strings ("this" and "this also" are Strings) that can be
  # used when running scripts, events, or other features; as a way to distinguish
  # between certain players. (Like that of actual Minecraft tags that Mojang
  # introduced in 1.13.) --> (Link below for the Minecraft version -- NOT Streamline!)
  # https://www.digminecraft.com/game_commands/tag_command.php#:~:text=You%20can%20add%2C%20list%20and,and%20manage%20tags%20for%20players.
  tags:
    # The default tags a user will receive when their profile is first created.
    default: []

# The settings for debugging the plugin.
debug:
  # Notifications for...
  notify-on:
    # Whether we should notify you about how to get modules if your 'modules' folder is empty.
    no-modules: true
  console:
    info:
      full-disable: false
      prefix: "&f[&3StreamlineCore&f] &r"
    warnings:
      full-disable: false
      prefix: "&f[&3StreamlineCore&f] &6"
    errors:
      full-disable: false
      prefix: "&f[&3StreamlineCore&f] &c"
    debug:
      full-disable: true
      prefix: "&f[&3StreamlineCore&f] &f[&cDEBUG&f] &r"