modLoader="javafml"
loaderVersion="[36,)"
license="MIT"

[[mods]]
    modId="streamlinecore"
    version="${version}"
    displayName="${name}"
    description="StreamlineCore Forge implementation"

[[dependencies.streamlinecore]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="SERVER"

[[dependencies.streamlinecore]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="SERVER"
