org.gradle.parallel=true
org.gradle.jvmargs=-Xmx4g

group = com.github.streamline-essentials
version = 1.0.0
name = StreamlineGroups
include-bapi = false

# Project Stuff.
streamline.version = 2.5.5.5

pf.class = host.plas
pf.id = streamline-groups
pf.requires = none
pf.dependencies = none
pf.description = Groups Module for StreamlineCore.
pf.provider = Drakify
pf.license = Apache License 2.0