modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
    modId="streamlinecore"
    version="${version}"
    displayName="${name}"
    description="StreamlineCore Forge implementation"

[[dependencies.streamlinecore]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="SERVER"

[[dependencies.streamlinecore]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="SERVER"
