# Main Stuff.
name = MobGriefControl
group = com.github.streamline-essentials
version = 1.0.0
include-bapi = true

# PF4J Stuff.
pf.class = host.plas
pf.id = mob-grief-control
pf.requires = none
pf.dependencies = none
pf.description = Stops creepers, ghasts, endermen and withers from griefing blocks, with per-mob entity damage toggles.
pf.provider = Drak
pf.license = Apache License 2.0
