dependencies {
    // Platform Backend.
    compileOnly 'org.spigotmc:spigot-api:1.16.5-R0.1-SNAPSHOT'

    // Defaults.
    compileOnly(files(FILES))
    annotationProcessor(ANNO)
    annotationProcessor(THE_BASE)
    compileOnly(COMP_ONLY)
    compileOnly(PLATFORM_LIBRARIES)

    // Other Plugins
    compileOnly(OTHER_PLUGINS)

    // The Base / BOU
    compileOnly("gg.drak:BukkitOfUtils:${rootProject.properties["bou_version"]}")

    // Thin Streamline API (includes singularity classes; no Maven Central libs).
    implementation project(path: ':StreamlineCore-API', configuration: 'shadow')

    compileOnly "me.clip:placeholderapi:${rootProject.properties["papi_version"]}"

    // Files.
    compileOnly(files(FILES))
}

compileJava {
    dependsOn(":StreamlineCore-API:shadowJar")
}

delombok {
    dependsOn(":StreamlineCore-API:shadowJar")
}
