package singularity.data.players.location;

import lombok.Getter;
import lombok.Setter;

/**
 * Represents an integer block coordinate triplet (x, y, z) in a Minecraft world.
 *
 * <p>{@code BlockPosition} is a lightweight, comparable value object used throughout
 * the Streamline framework wherever a discrete world position is required. All three
 * coordinate fields and their accessors are generated by Lombok via
 * {@code @Getter}/{@code @Setter}.</p>
 *
 * <p>Instances are naturally ordered first by X, then Y, then Z (ascending), making
 * them suitable for use in sorted collections.</p>
 */
@Getter @Setter
public class BlockPosition implements Comparable<BlockPosition> {

    /** The X (east/west) coordinate of this block position. */
    private int x;

    /** The Y (up/down) coordinate of this block position. */
    private int y;

    /** The Z (north/south) coordinate of this block position. */
    private int z;

    /**
     * Constructs a {@code BlockPosition} with the given integer coordinates.
     *
     * @param x the X coordinate
     * @param y the Y coordinate
     * @param z the Z coordinate
     */
    public BlockPosition(int x, int y, int z) {
        this.x = x;
        this.y = y;
        this.z = z;
    }

    /**
     * Compares this position with another, ordering by X, then Y, then Z.
     *
     * @param o the other {@code BlockPosition} to compare against
     * @return a negative integer, zero, or a positive integer as this position
     *         is less than, equal to, or greater than the specified position
     */
    @Override
    public int compareTo(BlockPosition o) {
        if (x != o.x) return x - o.x;
        if (y != o.y) return y - o.y;
        return z - o.z;
    }

    /**
     * Calculates the Euclidean (straight-line) distance between this position
     * and the given {@code other} position.
     *
     * @param other the target {@code BlockPosition}
     * @return the distance in blocks as a {@code double}
     */
    public double distance(BlockPosition other) {
        return Math.sqrt(Math.pow(x - other.x, 2) + Math.pow(y - other.y, 2) + Math.pow(z - other.z, 2));
    }

    /**
     * Converts this {@code BlockPosition} into a {@link WorldPosition} using the
     * same integer coordinates. The resulting {@link WorldPosition} has no world
     * name assigned.
     *
     * @return a new {@link WorldPosition} with the same x, y, z values
     */
    public WorldPosition asWorldPosition() {
        return new WorldPosition(x, y, z);
    }
}
