modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mods]]
    modId="streamlinecore"
    version="${version}"
    displayName="${name}"
    description="StreamlineCore NeoForge implementation"

[[dependencies.streamlinecore]]
    modId="neoforge"
    type="required"
    versionRange="[21.1,)"
    ordering="NONE"
    side="SERVER"

[[dependencies.streamlinecore]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1,1.21.2)"
    ordering="NONE"
    side="SERVER"
