enabled: false

# Settings for saving users.
saving:
  # The type of storage to use.
  # Can be:
  # YAML (Default) (Flat file)
  # JSON (Flat file)
  # TOML (Flat file)
  # MONGO (NoSQL database)
  # MYSQL (SQL database)
  use: JSON
  # Settings for only if using MONGO or MYSQL above.
  databases:
    # Connection URL for connecting to the database.
    connection-uri: "mongodb://<user>:<pass>@<host>:<port>/?authSource=admin&readPreference=primary&appname=StreamlineAPI&ssl=false"
    # The actual database to use.
    database: "streamline_users"
    # The table (MYSQL) or collection (MONGO) prefix.
    prefix: "sl_"