# Main Stuff.
name = StreamersUnite
group = com.github.streamline-essentials
version = 1.3.1
include-bapi = false

# Project Stuff.
streamline.version = 2.5.4.0

# PF4J Stuff.
pf.class = host.plas
pf.id = streamers-unite
pf.requires = none
pf.dependencies = none
pf.description = Streaming made easy with StreamlineCore.
pf.provider = Drak
pf.license = Apache License 2.0