# Main Stuff.
name = TacoEssentials
group = gg.drak
version = 1.0.0
include-bapi = false

# Project Stuff.
streamline.version = 2.5.6.0

# PF4J Stuff.
pf.class = gg.drak.tacoessentials
pf.id = taco-essentials
pf.requires = none
pf.dependencies = none
pf.description = Essential commands (teleports, homes, warps, utilities and moderation) for StreamlineCore.
pf.provider = Drak
pf.license = Apache License 2.0
