name: Auto Create Pull Request

on:
  push:
    branches:
      - dev

jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create Pull Request
      uses: repo-sync/pull-request@v2
      with:
        source_branch: dev
        destination_branch: master
        pr_title: "Auto PR: Merge dev into master"
        pr_body: "This PR merges changes from dev into master."
        github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
