name: Auto Merge Pull Request

on:
  pull_request:
    branches:
      - master
    types:
      - opened
      - synchronize

jobs:
  auto-merge:
    runs-on: ubuntu-latest

    steps:
    - name: Check for merge conflicts
      run: |
        git fetch origin master
        git merge --no-commit --no-ff dev || exit 1

    - name: Auto Merge Pull Request
      uses: pascalgn/automerge-action@v0.15.3
      with:
        github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
